# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c19917b4a2debee7883b9c98737918e9cbbd8cdfe32dd3ec0a143131c79efeac92224b71e022dd2d94757add131e1d62181b53091b19694b19ba2e70d9279c6b

test:
  secret_key_base: 20b94a5024ccfd223e0a593132b5014846225241e7c905fa91ece8cc42f15805aae7a9f44976434e3db133d73a9525453e382462cf172d1dc6587b1941fe1f7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
